### ISSUE TITLE
Implementing Rating

### ISSUE THREAD

**Issue by sharyar** [CMPUT301W20T29-H03/ZoomWroom#14]
I am wondering what would be the best approach to implementing ratings. 
We can go about it several ways: 

1. Ratings have attributes regarding Driver, Rider & DriveRequest. This way we can look through the ratings and find ones associated with a particular driver. 
2. Rating has an attribute for DriveRequest. Then we can find the rider and driver via the drive request. 
3. DriveRequest has one instance of rating. The rating has no attributes except boolean for thumbsup or down. If we want to find the ratings for a driver, we go through their drive requests.

I am not exactly certain which way is best. The simplest is the first one however the last one has the least amount of coupling.  The current implementation is based on the first approach however we can change this.

**Comment by amandanguyeen** [comment]
I think #3 would be best. I may be misinterpreting things, but #1 seems like users go through ratings then find drivers instead of drivers then finding certain ratings. #3 is also the most intuitive way I would think to find ratings for the driver. Since we only need to find/calculate drivers ratings, if drivers have their own profile we can search through, it'll make that calculation a lot simpler rather than parsing through Ratings then finding driver from there!

**Comment by DulongSang** [comment]
Closed by #74
