### ISSUE TITLE
Driver profile does not open on username

### ISSUE THREAD

**Issue by amandanguyeen** [CMPUT301W20T29-H03/ZoomWroom#194]
"As a user, I want to, when a username is presented for a thing, retrieve and show its contact information"

The profile opens on the driver's name which is incorrect. It needs to open on the driver's username.

**Comment by DulongSang** [comment]
I can fix it, but it is kinda weird if we click the username TextView to open the contact since the full name TextView is larger than the username TextView. I do not think the user story is rigid.
By the way, on the driver side, the rider's username is not displayed in the current request, only the full name.

**Comment by amandanguyeen** [comment]
I'll leave it as their name then. I'll close this issue and bring up the rider's username on slack

**Comment by amandanguyeen** [comment]
Actually even if its not rigid, it's better to follow the user story and have the info linked to their username. I can fix this while I'm fixing the other bug as well

**Comment by DulongSang** [comment]
> Actually even if its not rigid, it's better to follow the user story and have the info linked to their username. I can fix this while I'm fixing the other bug as well

OK, I will fix it. Both username and full name can open the contact info.

**Comment by amandanguyeen** [comment]
It's okay Dulong it's a one-liner fix and I have to submit a pull request for the other bug as well so I can do it

**Comment by DulongSang** [comment]
got it, thank you.
